### ISSUE TITLE
Thermistors tables are not accurate - need to be updated 

### ISSUE THREAD

**Issue by codehero** [luc-github/Repetier-Firmware#83]
Extruder thermistor needs heatup sequence similar to heated bed

background here: http://voltivo.com/forum/davinci-peersupport/372-extruder-and-bed-do-not-heat-up

**Comment by luc-github** [comment]
Thanks a lot ^_^

**Comment by luc-github** [comment]
OK after implementation they are good for room temperature 16 - 22 - so I have tweaked them a little
and did some print also to check - I did some pid check at 110 for bed and 230 for extruders and oscillations are not bad 
I also did a print of ABS at 95/110 during 2h and was also good
so here the tables I will push to FW 
Bed Gen 0/1 
![image](https://cloud.githubusercontent.com/assets/8822552/5594945/fe1cd7d6-929f-11e4-813e-7fd14055c177.png)
#define NUM_TEMPS_USERTHERMISTOR1 19
#define USER_THERMISTORTABLE1 {{628,1280},{859,1200},{1113,1120},{1382,1040},{1660,960},{1938,880},{2211,800},{2473,720},{2718,640},{2945,560},{3148,480},{3328,400},{3482,320},{3613,240},{3722,160},{3815,80},{3895,0},{3972,-80},{4055,-160}}

Extruder Gen 0
![image](https://cloud.githubusercontent.com/assets/8822552/5594948/228fa7c4-92a0-11e4-8a05-5b3d88357639.png)
#define NUM_TEMPS_USERTHERMISTOR0 33
#define USER_THERMISTORTABLE0 {{96,2400},{99,2320},{113,2240},{132,2160},{155,2080},{180,2000},{211,1920},{247,1840},{293,1760},{350,1680},{421,1600},{508,1520},{611,1440},{732,1360},{871,1280},{1024,1200},{1192,1120},{1369,1040},{1552,960},{1737,880},{1900,800},{2070,720},{2219,640},{2361,560},{2478,480},{2565,400},{2628,320},{2673,240},{2710,160},{2746,80},{2783,0},{2824,-80},{2864,-160}}

I will add the excel file in sources for reference

**Comment by luc-github** [comment]
I have applied it to 0.92 only

**Comment by luc-github** [comment]
So far so good - so i close now
