### ISSUE TITLE
Support new DaVinci 1.0 AiO based

### ISSUE THREAD

**Issue by Doudou14** [luc-github/Repetier-Firmware#85]
hello

As you have seen, the motherboard DaVinci 1.0 is now based on the AIO. Should adapt the firmware to be compatible.
These are just the pins that have changed?

**Comment by luc-github** [comment]
Implemented in 0.92 https://github.com/luc-github/Repetier-Firmware-0.92

**Comment by Doudou14** [comment]
I confirm that everything works

**Comment by luc-github** [comment]
You have also a 1.0A ?

**Comment by Doudou14** [comment]
No, but I know someone who has it and everything works
(Unless the lighting but I do not know if he has activated)

**Comment by luc-github** [comment]
Light is one of the pin modifications gave by ogremustcrush so should be ok
