### ISSUE TITLE
Occasional firmware crash during ABL

### ISSUE THREAD

**Issue by axs-gentoo** [luc-github/Repetier-Firmware#88]
daVinci 1.0, fan mod, repetier-firmware-0.91 custom built from master, one commit prior to beta2 release.

I've had a couple of issues as of late with this firmware -- specifically, when I do the auto-bed-levelling run more than once, then sometimes, when the firmware prompts to save the z-offset adjustment, everything locks up and I need to do a power-off-reset.  I believe this only occurs when I answer 'yes' to save the new z-offset.  Certainly it doesn't happen all the time, as I regularly run ABL multiple times in a row without issue.

I don't know if the lockup relates to an eeprom-write that's failing or if it's something else; I'm certainly willing to help diagnose the issue but I don't know what I can do to debug it.  Any suggestions/advice/steps to get a log for you would be appreciated.

**Comment by axs-gentoo** [comment]
I have no updates, have had very little access to the printer over the past couple of weeks.  It hasn't crashed on me during ABL since I've reported the bug; i did have my first mid-print crash but that's it so far.  I think this could be considered a long-term tracking issue and it probably shouldn't hold up any pending releases.

**Comment by luc-github** [comment]
Ok, so I left like this, I will release the 1.0 (0.91) to golden release and move 1.1 (0.92) to beta next week .
I will more focus on 1.1 by then and move all issues to 1.1 if necessary

**Comment by luc-github** [comment]
Ok I am late in schedule due to LCD panel issues but should be back on track now, so will release 1.0 as it is = same as RC , I have moved all issue but this one to 0.92/1.1 already

**Comment by luc-github** [comment]
Close as not reproduced
